FROM alpine:3.22.2

RUN apk add wget
RUN apk add openjdk21-jre
RUN apk add bash
RUN apk add python3

RUN mkdir /scripts
COPY initserver.sh /scripts
COPY runserver.sh  /scripts
COPY setupFIFOs.py /scripts
COPY forwarding.py /scripts

COPY setup.sh /

ENTRYPOINT [ "/setup.sh" ]
